"""add_filter_indexes

Revision ID: 78d4308e075a
Revises: 7131439d0abc
Create Date: 2026-05-19 07:00:27.178200

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '78d4308e075a'
down_revision: Union[str, Sequence[str], None] = '7131439d0abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_priority', 'projects', ['priority'], unique=False)
    op.create_index('ix_projects_status_priority', 'projects', ['status', 'priority'], unique=False)
    op.create_index('ix_team_members_role_seniority', 'team_members', ['role', 'seniority'], unique=False)
    op.create_index('ix_team_members_seniority', 'team_members', ['seniority'], unique=False)
    op.create_index('ix_team_members_status', 'team_members', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_members_status', table_name='team_members')
    op.drop_index('ix_team_members_seniority', table_name='team_members')
    op.drop_index('ix_team_members_role_seniority', table_name='team_members')
    op.drop_index('ix_projects_status_priority', table_name='projects')
    op.drop_index('ix_projects_priority', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    # ### end Alembic commands ###
